name: Backend CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install black ruff mypy pydantic pydantic-settings

      - name: Run Black
        run: black --check .

      - name: Run Ruff
        run: ruff check app

      - name: Run MyPy
        run: mypy app