name: Saas Backend CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install black==24.3.0 ruff==0.4.4 mypy==1.10.0 pydantic pydantic-settings

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run Black
        run: black --check --diff .

      - name: Run Ruff
        run: ruff check app

      - name: Run MyPy
        run: mypy app